### ISSUE TITLE
Identify Key DataRefs for Pilot Performance

### ISSUE THREAD

**Issue by harshitha-thota** [oss-slu/PilotDataSynchronization#2]
Research and document the essential DataRefs in the flight simulator that are critical for capturing pilot performance data, specifically focusing on Altitude, Airspeed, Vertical Airspeed, and Heading. This will aid in synchronization with the iMotions platform.

Acceptance Criteria:

A detailed list of DataRefs for Altitude, Airspeed, Vertical Airspeed, and Heading.
Documentation includes the DataRef name, purpose, data type, usage.

**Comment by kungfuchicken** [comment]
this is a big rock
