### ISSUE TITLE
Generating an xml using active datarefs

### ISSUE THREAD

**Issue by harshitha-thota** [oss-slu/PilotDataSynchronization#30]
Given the flight simulator
When the dataref extracts the data
Then the xml file should be generated dynamically using the selected datarefs.

Developer Notes:
Generate a XML(refer to the iMotions Programmer guide 27-30)
```
<EventSource Version=”1” Id=”QSensor” Name=”Affectiva Q Sensor”>
    <Sample Id=”AffectivaQSensor” Name=”QSensor”>
        <Field Id=”SeqNo” /> 
        <Field Id=”AccelZ” />
        <Field Id=”AccelY” />
        <Field Id=”AccelX” />
        <Field Id=”Battery” />
        <Field Id=”Temperature” Range=”Fixed” Min=”30” Max=”40” />
        <Field Id=”EDA” Range=”Variable” Min=”0” Max=”0.2” />
    </Sample>
</EventSource>
```

Acceptance Criteria:

- [ ] Generates an Xml file
- [ ] Xml file should follow the dataformat
- [ ] the list of Field Ids matches the dataref?

**Comment by aelnourSLU** [comment]
Dynamic generation will have to wait until we have our datarefs and desired config layout finalized. We can discuss that at the next team meeting. For now, I've added a simple one-liner function that returns a string, which we can edit as needed until it's time to add dynamic substitutions. At that time, I will reopen this issue.
